using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.collection.family_.ring_.sigma_
{
	/// <summary>
	/// For some family X, the intersection of all σ-fieldS
	///		, each of which , denoted as A[i], contains X, or in other words, satisfies:
	///			 x ∈X => x ∈ A[i] for all i
	///	 ,
	///	 is itself a σ-algebra, denoted σ(X). This is called the σ-field generated by X.
	/// </summary>
	class Generated<T>
	   : nilnul.obj.Box1<T>
	   where T : nilnul.collection.IFamily
	{
		public Generated(T val) : base(val)
		{
		}
	}
}
